name: Continuous Integration

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.gitignore'
      - '**.dockerignore'
      - '**/README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.gitignore'
      - '**.dockerignore'
      - '**/README.md'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-20.04, macos-11.0, windows-2019]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
