# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
name: Node CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.gitignore'
      - '**/README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.gitignore'
      - '**/README.md'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash --noprofile --norc -x -eo pipefail {0}
        working-directory: ../NotMe/NotMe.Client
    strategy:
      matrix: 
        os: [ubuntu-20.04, macos-11.0, windows-2019]
        node-version: [15.x, 14.x, 12.x]
        
    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
      working-directory: ../NotMe/NotMe.Client
    - run: npm run build --if-present
      working-directory: ../NotMe/NotMe.Client
    - run: npm test
      working-directory: ../NotMe/NotMe.Client
      
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
